### ISSUE TITLE
As Paas-ops, I want to receive an email on each new space creation so that I can track space creation

### ISSUE THREAD

**Issue by o-orand** [Orange-OpenSource/elpaaso-sandbox-ui#3]
As a Paas-ops:
- I want to receive only one email on each new space creation,
- I should be able to set a single email address or a list of email,
- I should be able to disable this notification,

**Technical**
- [Spring Boot email](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-email.html)

**Comment by o-orand** [comment]
It is also possible to use [CF Notifications](https://github.com/cloudfoundry-incubator/notifications#notifications). Using this solution requires as prerequisite to have CF Notifications available. But it seems that Notifications Bosh release  is only automated on AWS (need a manual manifest generation). @poblin-orange. Requires this release to prototype.

**Comment by gberche-orange** [comment]
closed in favor of https://github.com/Orange-OpenSource/elpaaso-sandbox-service/issues/8
